### ISSUE TITLE
Manque shp2pgsql sur des backends osmose

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#107]
http://buildbot.osmose.openstreetmap.fr/builders/france_ile_de_france_yvelines/builds/56/steps/osmose_run.py/logs/stdio

osm212

```
2019-05-01 08:06:31   error: error on analyse merge_bicycle_rental_FR_IDF...
2019-05-01 08:06:31     Traceback (most recent call last):
2019-05-01 08:06:31       File "./osmose_run.py", line 230, in execc
2019-05-01 08:06:31         analyser_obj.analyser()
2019-05-01 08:06:31       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 188, in analyser
2019-05-01 08:06:31         self.analyser_osmosis_common()
2019-05-01 08:06:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 834, in analyser_osmosis_common
2019-05-01 08:06:31         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2019-05-01 08:06:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 611, in run
2019-05-01 08:06:31         parser.import_(table, self.srid, osmosis)
2019-05-01 08:06:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 518, in import_
2019-05-01 08:06:31         raise Exception("shp2pgsql error")
```

**Comment by jocelynj** [comment]
La commande est bien installé:
```
jocelyn@osm212:~$ /usr/bin/shp2pgsql
RELEASE: 2.3.1 (r15264)
```

**Comment by frodrigo** [comment]
Le problème doit être autre chose alors, mais le message d'erreur n'aide pas vraiement...

**Comment by frodrigo** [comment]
Problème sur le source de données SHP qui retourne alétoirement des données.
