### ISSUE TITLE
Installer ogr2ogr (gdal-bin) pour Osmose

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#265]
Les backend qui font tourner les analyses IGN Osmose ont besoin de ogr2ogr
```
2021-02-06 06:44:38 france_guyane : merge_poi_FR
2021-02-06 06:44:38   error: Fails to get status from frontend: 404
2021-02-06 06:44:38   run osmosis all analyser SubAnalyser_Merge_POI_FR_10001
2021-02-06 06:44:38   Analyser_Merge.py:1130 sql
2021-02-06 06:44:38   Analyser_Merge.py:766 sql
2021-02-06 06:44:38   Analyser_Merge.py:771 sql
2021-02-06 06:44:38   Load source into database
2021-02-06 06:44:38   Analyser_Merge.py:774 sql
2021-02-06 06:44:38   Analyser_Merge.py:782 sql
sh: 1: ogr2ogr: not found
ogr2ogr -f PostgreSQL 'PG:dbname=osmose user=osmose password=-osmose- options=--search_path=france_guyane,public ' -lco SCHEMA=osmose -nln poi_fr -lco OVERWRITE=yes -lco GEOMETRY_NAME=geom -lco UNLOGGED=ON -t_srs EPSG:4326 '/tmp/tmpdz5fb_36' 
2021-02-06 06:44:43   error: error on analyse merge_poi_FR...
2021-02-06 06:44:43     Traceback (most recent call last):
2021-02-06 06:44:43       File "./osmose_run.py", line 262, in execc
2021-02-06 06:44:43         analyser_obj.analyser()
2021-02-06 06:44:43       File "/data/project/osmose/backend/analysers/Analyser_Merge_Dynamic.py", line 44, in analyser
2021-02-06 06:44:43         analyser_obj.analyser()
2021-02-06 06:44:43       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2021-02-06 06:44:43         self.analyser_osmosis_common()
2021-02-06 06:44:43       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1131, in analyser_osmosis_common
2021-02-06 06:44:43         table = self.load.run(self, self.parser, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2021-02-06 06:44:43       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 785, in run
2021-02-06 06:44:43         parser.import_(table, self.srid, osmosis)
2021-02-06 06:44:43       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 720, in import_
2021-02-06 06:44:43         raise Exception("ogr2ogr error")
2021-02-06 06:44:43     Exception: ogr2ogr error
```

**Comment by jocelynj** [comment]
C'est une nouvelle dépendance ?

**Comment by jocelynj** [comment]
C'est installé sur tous les backends, et ajouté dans ansible: https://github.com/osm-fr/ansible-scripts/commit/e882178aa6e5c508a5d6c8dffef69d792d9df8fd
