### ISSUE TITLE
Prblème versoin base de données backend Osmose sur ca-davin0[34]

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#266]
Problème version base de données backend Osmose sur ca-davin0[34]

```
DB connection fails, retry...
2021-02-08 00:02:28 error: error in database initialisation
2021-02-08 00:02:28 cleaning : 
2021-02-08 00:02:28 end of analyses
Traceback (most recent call last):
  File "./osmose_run.py", line 380, in run
    osmosis_manager = modules.OsmOsisManager.OsmOsisManager(conf, conf.db_host, conf.db_user, conf.db_password, conf.db_base, conf.db_schema or conf.country, conf.db_persistent, logger)
  File "/data/project/osmose/backend/modules/OsmOsisManager.py", line 63, in __init__
    if not self.check_database():
  File "/data/project/osmose/backend/modules/OsmOsisManager.py", line 139, in check_database
    gisconn = self.osmosis(schema_path = False).conn()
  File "/data/project/osmose/backend/modules/OsmOsisManager.py", line 84, in osmosis
    self._osmosis = OsmOsis(self.db_string)
  File "/data/project/osmose/backend/modules/OsmOsis.py", line 39, in __init__
    self._PgConn = psycopg2.connect(dbstring)
  File "/data/project/osmose/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database locale is incompatible with operating system
DETAIL:  The database was initialized with LC_COLLATE "en_US.UTF-8",  which is not recognized by setlocale().
HINT:  Recreate the database with another locale or install the missing locale.
```

**Comment by jocelynj** [comment]
Un `apt dist-upgrade` a été lancé par l'admin de ces VMs, et ça a mis à jour la libc. J'ai relancé postgresql sur les 4 VMs davintech, et ça remarche.
