### ISSUE TITLE
Erreur mise à jour des extracts Osmose avec nouvelle versoin pyosmium-up-to-date

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#267]
Erreur mise à jour des extracts Osmose avec nouvelle versoin pyosmium-up-to-date

```
2021-02-08 11:28:37 iteration=10
2021-02-08 11:28:37   2021-02-08 11:28:37 INFO: Using replication service at http://download.openstreetmap.fr/replication/./europe/norway/aust-agder/minute
2021-02-08 11:28:37   2021-02-08 11:28:37 INFO: Starting download at ID 4404545 (max 1024 MB)
2021-02-08 11:29:53   Traceback (most recent call last):
2021-02-08 11:29:53   File "/usr/bin/pyosmium-up-to-date", line 246, in <module>
2021-02-08 11:29:53   ret = update_from_custom_server(url, seq, ts, options)
2021-02-08 11:29:53   File "/usr/bin/pyosmium-up-to-date", line 125, in update_from_custom_server
2021-02-08 11:29:53   outformat=options.outformat)
2021-02-08 11:29:53   File "/usr/lib/python3/dist-packages/osmium/replication/server.py", line 173, in apply_diffs_to_file
2021-02-08 11:29:53   h.set("osmosis_replication_timestamp", info.timestamp.strftime("%Y-%m-%dT%H:%M:%SZ"))
2021-02-08 11:29:53   AttributeError: 'NoneType' object has no attribute 'timestamp'
```

https://buildbot.osmose.openstreetmap.fr/#/builders/639/builds/172/steps/1/logs/stdio

**Comment by jocelynj** [comment]
J'avais annulé mon précédent fix, pour tester le nouveau fix présent sur https://github.com/osmcode/pyosmium/commit/2ac1c24d0bf15c95aa0dc836cadad27f3fb36074, mais j'avais pas mis le nouveau fix (je n'avais plus de problème réseau pour tester).
J'ai mis le fix officiel sur la VM aquilenet.
