### ISSUE TITLE
Echec de mise à jour des extracts Osmose

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#270]
Tous les examples que j'ai vu sont sur le backend aquilenet.

La mise à jour de l'extract échoue avec osmium
```
2021-02-24 15:06:43 iteration=1
2021-02-24 15:06:43   2021-02-24 15:06:43 INFO: Using replication service at http://download.openstreetmap.fr/replication/./europe/spain/andalucia/minute
2021-02-24 15:06:43   2021-02-24 15:06:43 INFO: Starting download at ID 4427536 (max 1024 MB)
2021-02-24 15:07:52   2021-02-24 15:07:52 INFO: Downloaded until 4427974. Server has data available until 4429673.
2021-02-24 15:07:52 waiting 2 minutes
2021-02-24 15:09:52 iteration=2
2021-02-24 15:09:53   2021-02-24 15:09:53 INFO: Using replication service at http://download.openstreetmap.fr/replication/./europe/spain/andalucia/minute
2021-02-24 15:09:53   2021-02-24 15:09:53 INFO: Starting download at ID 4427536 (max 1024 MB)
2021-02-24 15:11:36   2021-02-24 15:11:36 INFO: Downloaded until 4428033. Server has data available until 4429673.
2021-02-24 15:11:36 waiting 2 minutes
2021-02-24 15:13:36 iteration=3
2021-02-24 15:13:36   2021-02-24 15:13:36 INFO: Using replication service at http://download.openstreetmap.fr/replication/./europe/spain/andalucia/minute
2021-02-24 15:13:36   2021-02-24 15:13:36 INFO: Starting download at ID 4427536 (max 1024 MB)
2021-02-24 15:15:18   2021-02-24 15:15:18 INFO: Downloaded until 4428033. Server has data available until 4429674.
2021-02-24 15:15:18 waiting 2 minutes
```

Les diff existent bien sur le serveur.
Le problème n'a pas l'air systématique.

https://buildbot.osmose.openstreetmap.fr/#/builders/396/builds/190
https://buildbot.osmose.openstreetmap.fr/#/builders/394/builds/188
https://buildbot.osmose.openstreetmap.fr/#/builders/26/builds/186

**Comment by jocelynj** [comment]
Ça ressemble vraiment à un souci de connectivité entre aquilenet et download :(

Il y a quand même un truc bizarre: sur les trois itérations, pyosmium reprend du numéro 4427536, au lieu de reprendre du dernier téléchargé précédemment. J'ai rajouté -vvv sur la commande pyosium-up-to-date pour y voir plus clair.

**Comment by jocelynj** [comment]
En fait, la reprise ne se fait pas au seqnum précédent, parce que pyosmium-up-to-date passe par un fichier temporaire, via:
```
          cmd  = [conf.bin_pyosmium_up_to_date]
          cmd += ["-v"]
          cmd += ["--outfile", tmp_pbf_file]
          cmd += ["--tmpdir", conf.dir_tmp]
          cmd += ["--force-update-of-old-planet"]
          cmd += [pbf_file]
          ret = self.logger.execute_err(cmd, valid_return_code=(0, 3))

          if ret == 0:
            shutil.move(tmp_pbf_file, pbf_file)
```
Je vais changer sur aquilenet pour faire le move avec l'erreur 1 aussi:
```
The program returns 0, if updates have been successfully applied up to
the newest data or no new data was available. It returns 1, if some updates
have been applied but there is still data available on the server (either
because the size limit has been reached or there was a network error which
could not be resolved). Any other error results in a return code larger than 1.
The output file is guaranteed to be unmodified in that case.
```

**Comment by jocelynj** [comment]
Ça a l'air mieux maintenant, d'après le log sur https://buildbot.osmose.openstreetmap.fr/#/builders/32/builds/188/steps/1/logs/stdio

J'ai appliqué ce diff:
```diff
--- a/modules/OsmOsisManager.py
+++ b/modules/OsmOsisManager.py
@@ -418,15 +418,21 @@ class OsmOsisManager:
 
         try:
           cmd  = [conf.bin_pyosmium_up_to_date]
-          cmd += ["-v"]
+          cmd += ["-vvv"]
           cmd += ["--outfile", tmp_pbf_file]
           cmd += ["--tmpdir", conf.dir_tmp]
           cmd += ["--force-update-of-old-planet"]
           cmd += [pbf_file]
-          ret = self.logger.execute_err(cmd, valid_return_code=(0, 3))
+          ret = self.logger.execute_err(cmd, valid_return_code=(0, 1, 3))
 
-          if ret == 0:
+          self.logger.log("pyosmium-up-to-date got ret=%d" % ret)
+
+          if ret == 0 or ret == 1:
             shutil.move(tmp_pbf_file, pbf_file)
+
+          if ret == 1:
+            # mean that we didn't fully update pbf file
+            raise Exception("Not fully updated")
         except:
           self.logger.log("waiting 2 minutes")
           time.sleep(2*60)
```

**Comment by frodrigo** [comment]
Je ne sais pas ou tu a mis ces modifications. Mais minetement il y a ça sur certain run. Vu que sur les VM ca-davin*.


```
2021-02-27 22:04:51 run pyosmium replication
state:  2021-02-23 04:31:16+00:00 2021-02-27 22:04:51 iteration=1
2021-02-27 22:04:51   2021-02-27 22:04:51 INFO: Using replication service at http://download.openstreetmap.fr/replication/./north-america/canada/ontario/central_ontario/minute
2021-02-27 22:04:52   2021-02-27 22:04:52 INFO: Starting download at ID 4427798 (max 1024 MB)
2021-02-27 22:25:01   Traceback (most recent call last):
2021-02-27 22:25:01   File "/usr/bin/pyosmium-up-to-date", line 246, in <module>
2021-02-27 22:25:01   ret = update_from_custom_server(url, seq, ts, options)
2021-02-27 22:25:01   File "/usr/bin/pyosmium-up-to-date", line 125, in update_from_custom_server
2021-02-27 22:25:01   outformat=options.outformat)
2021-02-27 22:25:01   File "/usr/lib/python3/dist-packages/osmium/replication/server.py", line 173, in apply_diffs_to_file
2021-02-27 22:25:01   h.set("osmosis_replication_timestamp", info.timestamp.strftime("%Y-%m-%dT%H:%M:%SZ"))
2021-02-27 22:25:01   AttributeError: 'NoneType' object has no attribute 'timestamp'
2021-02-27 22:25:02 waiting 2 minutes
2021-02-27 22:27:02 iteration=2
2021-02-27 22:27:02   2021-02-27 22:27:02 INFO: Using replication service at http://download.openstreetmap.fr/replication/./north-america/canada/ontario/central_ontario/minute
2021-02-27 22:27:34   2021-02-27 22:27:34 ERROR: Cannot download state information for ID 4427797. Is the URL correct?
state:  2  -  2021-02-23 04:31:16+00:00     0:00:00
```

https://buildbot.osmose.openstreetmap.fr/#/builders/226/builds/193

**Comment by jocelynj** [comment]
J'ai fait la modif ci-dessus uniquement sur la VM aquilenet. Si ça te convient, je peux faire un PR sur osmose-backend.

L'erreur que tu as vu sur ca-davin*. est la même que celle qu'on avait il y a qq temps sur aquilenet, et corrigée par https://github.com/osmcode/pyosmium/commit/2ac1c24d0bf15c95aa0dc836cadad27f3fb36074, du moins pour iteration=1. Pour iteration=2, ça ne me parait pas normal: osmose_run.py aurait du retenter un update sur l'itération suivante.

**Comment by frodrigo** [comment]
Ok pour le patch. Remplace juste le % par un format ou une f-string.

**Comment by jocelynj** [comment]
Pour l'erreur sur ca-davin, j'ai compris le scénario:
   - pyosmim-up-to-date a retourné une erreur 3, parce qu'il n'a pas pu télécharger le state.txt du serveur
   - on considère que c'est une erreur autorisée (parce qu'elle est retournée avec pyosmium < 3.1.3 si il n'y a pas de mise à jour à faire)
   - OsmOsisManager.py a mis `is_uptodate = True` à cause de la vérification sur `elif prev_timestamp == cur_timestamp:`

Je n'ai pas de solution à proposer, tant qu'on ne passe pas à pyosmium version 3.1.3 qui contient ce fix https://github.com/osmcode/pyosmium/commit/6c9e7691a551cf8fc18959b4c44b9eb9cf69c14a, et qui permettra de marquer l'erreur 3 comme une vraie erreur.

**Comment by frodrigo** [comment]
> Je n'ai pas de solution à proposer, tant qu'on ne passe pas à pyosmium version 3.1.3 qui contient ces fixes: [osmcode/pyosmium@56c10da](https://github.com/osmcode/pyosmium/commit/56c10dacbd31644511485bc36b965423ad4278dc) [osmcode/pyosmium@6c9e769](https://github.com/osmcode/pyosmium/commit/6c9e7691a551cf8fc18959b4c44b9eb9cf69c14a), et qui permettra de marquer l'erreur 3 comme une vraie erreur.

Il faut passer par un pip install ? On ne peut pas le faire ?

**Comment by jocelynj** [comment]
Pour la version 3.1.3, ça va arriver sous peu dans les backports debian: https://tracker.debian.org/pkg/pyosmium, et on pourra facilement l'installer sur tous les backends.

**Comment by jocelynj** [comment]
J'ai installé la version 3.1.3 de pyosmium sur tous les backends osmose auquel j'ai accès.
