### ISSUE TITLE
500 sur Osmose

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/infrastructure#345]
http://osmose.openstreetmap.fr/en/login

Du coup on peut modifier mais pas sauvegarder. Ce qui est une restriction d'utilisation^^.

Selon https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France ça devrait marcher.

**Comment by jocelynj** [comment]
Le log apache montre une erreur python:
```
Traceback (most recent call last):
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/data/project/osmose/frontend/modules/bottle_cors.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/data/project/osmose/frontend/modules/bottle_gettext.py", line 99, in wrapper
    return callback(*args, **kwargs)
  File "/data/project/osmose/frontend/web_api/app.py", line 71, in login
    (url, oauth_tokens) = oauth.fetch_request_token()
  File "/data/project/osmose/frontend/web_api/tool/oauth.py", line 28, in fetch_request_token
    request_token, request_token_secret = oauth.get_request_token()
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/rauth/service.py", line 244, in get_request_token
    process_token_request(r, decoder, key_token, key_token_secret)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/rauth/service.py", line 20, in process_token_request
    data = decoder(r.content)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/rauth/utils.py", line 26, in parse_utf8_qsl
    for k, v in d.items():  # pragma: no cover
RuntimeError: dictionary keys changed during iteration
```

**Comment by jocelynj** [comment]
Cette erreur est sur la librairie rauth, qui n'est plus maintenu, et lié au passage à python3.9: https://github.com/litl/rauth/issues/207

@frodrigo: est-ce qu'on devrait passer à une librairie maintenue, en utilisant oauth2 ?

En attendant, on peut toujours faire un clone git en récupérant les fixes nécessaires.

**Comment by frodrigo** [comment]
Oui, maintement c'est possible de passer à oauth2.

C'était une version patché de rauth qui est utilisé
https://github.com/osm-fr/osmose-frontend/blob/master/requirements.txt#L8-L9

On a bien toujours la même après mise à jour du serveur ?

**Comment by jocelynj** [comment]
Cette version patchée a le même bug: https://github.com/hendi/rauth/blob/master/rauth/utils.py#L30

Il faudrait qu'on récupére ce fix: https://github.com/litl/rauth/pull/208/files

**Comment by frodrigo** [comment]
Oui en attendant de faire la migration on peut faire un fork avec les deux patchs.

**Comment by jocelynj** [comment]
J'ai cloné sur https://github.com/osm-fr/rauth, et mis à jour requirements.txt sur le frontend.

Par contre, je ne peux plus tester si le login marche, parce que le bouton "logout" ne marche pas :(

**Comment by frodrigo** [comment]
J'ai testé la connection et ça marche.
C'est dans un cookies de session.

**Comment by Bibi56** [comment]
Je confirme, ça remarche. Merci tous les deux.
