### ISSUE TITLE
JOSM : Pb accès couche Ortho HR en IPv6

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/infrastructure#384]
Bonjour, j'ai des soucis avec JOSM pour charger la couche photo Ortho HR en IPv6. 

Dans les logs de JOSM, j'ai des exceptions du style :
```
2022-07-17 08:54:38.778 AVERTISSEMENT: java.net.NoRouteToHostException: Aucun chemin d'accès pour atteindre l'hôte cible
java.net.NoRouteToHostException: Aucun chemin d'accès pour atteindre l'hôte cible
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
```

en IPv4 c'est OK :

```
$ ping -4 wms.openstreetmap.fr
PING  (193.200.42.123) 56(84) octets de données.
64 octets de 193.200.42.123 (193.200.42.123) : icmp_seq=1 ttl=56 temps=34.7 ms
64 octets de 193.200.42.123 (193.200.42.123) : icmp_seq=2 ttl=56 temps=35.0 ms
^C
--- statistiques ping  ---
2 paquets transmis, 2 reçus, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 34.723/34.873/35.023/0.150 ms
```
Mais pas en IPv6 :

```
$ ping -6 wms.openstreetmap.fr
PING wms.openstreetmap.fr(2001:67c:1740:9031:1::123 (2001:67c:1740:9031:1::123)) 56 octets de données
De 2001:4d98:a000::95 (2001:4d98:a000::95) icmp_seq=1 Destination injoignable : Adresse injoignable
De 2001:4d98:a000::95 (2001:4d98:a000::95) icmp_seq=5 Destination injoignable : Adresse injoignable
De 2001:4d98:a000::95 (2001:4d98:a000::95) icmp_seq=9 Destination injoignable : Adresse injoignable
^C
--- statistiques ping wms.openstreetmap.fr ---
11 paquets transmis, 0 reçus, +3 erreurs, 100% packet loss, time 10280ms
```

## Palliatif
Pour l'instant, à titre de palliatif, j'ai désactivé l'accès IPv6 dans JOSM, en positionnant « prefer.ipv6=false » dans les paramètres avancés, ce qui permet une utilisation normale de JOSM.

**Comment by MikiDi** [comment]
Même chose ici. J'ai signalé https://listes.openstreetmap.fr/wws/arc/tech/2022-07/msg00000.html , mais il semble alors que c'est plus large. Merci pour le workaround.

**Comment by jocelynj** [comment]
Il y avait une erreur sur la config ipv6 sur le DNS. C'est normalement corrigé, merci @cquest.

**Comment by laurentriffard** [comment]
Bonjour,
j'ai réactivé l'accès IPv6 dans JOSM, en positionnant « prefer.ipv6=auto ». 
L’accès à Ortho HR est redevenu normal, toutes les tulles s'affichent bien.
Un « ping -6 wms.openstreetmap.fr » refonctionne aussi normalement.

Merci
