### ISSUE TITLE
download.openstreetmap.fr minutely diffs not updating

### ISSUE THREAD

**Issue by RicoElectrico** [osm-fr/infrastructure#56]
Hi, it seems that minutely diffs at download.openstreetmap.fr don't update since Aug 27.

E.g. http://download.openstreetmap.fr/replication/europe/poland/minute/state.txt

**Comment by jocelynj** [comment]
Thanks for reporting the issue.

The update process failed for an unknown reason - might be linked to another process running at the same time which got a disk-space error.

**Comment by jocelynj** [comment]
For reference, the error message is the following one:
```
Mon, 27 Aug 2018 20:24:11 +0200 (CEST)  

Traceback (most recent call last):                                                                                                                                                                                 
  File "./update.py", line 316, in <module>                                                                                                                                                                        
    update(wanted_end_sequence)                                                                                                                                                                                    
  File "./update.py", line 273, in update                                                                                                                                                                          
    r.get()                                                                                                                                                                                                        
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get                                                                                                                                              
    raise self._value                                                                                                                                                                                              
ValueError: could not convert string to float: Connexion   
```

**Comment by RicoElectrico** [comment]
Thanks, the updates work fine just now.

One question: if I maintain a database based on your diffs, would there be any missing data? Shall I re-import?

**Comment by jocelynj** [comment]
No, there will be no missing data.

When the update process crashes, it doesn't modify state.txt file, so when it is restarted, it begins before the "crashing" diff.
