### ISSUE TITLE
Panne de mobilizon suite à reboot de la VM associée

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#576]
http://mobilizon.openstreetmap.fr affiche une page d’erreur après un reboot de la VM (pour préparer une migration sur un autre cluster).

@tykayn, @pyrog: est-ce que vous pourriez regarder pourquoi ça ne marche pas, et si il y a un truc à faire après la future migration ?

**Comment by jocelynj** [comment]
Il y avait des erreurs sur des fichiers appartenant à root, que j’ai changé pour mobilizon:
```
/data/work/mobilizon/live/lib/mix/tasks/mobilizon/maintenance/fix_unattached_media_in_body.ex
/data/work/mobilizon/live/lib/mobilizon/todos/todos.ex
```

Mais ça plante encore, sur cette erreur:
```
Jul 06 20:49:00 mobilizon mobilizon[4092]: Request: GET /
Jul 06 20:49:00 mobilizon mobilizon[4092]: ** (exit) an exception was raised:
Jul 06 20:49:00 mobilizon mobilizon[4092]:     ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for {:error, :enoent} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Time, Tuple
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (phoenix_html 2.14.3) lib/phoenix_html/safe.ex:99: Phoenix.HTML.Safe.Tuple.to_iodata/1
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (phoenix 1.5.7) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (mobilizon 1.0.7) lib/web/controllers/page_controller.ex:1: Mobilizon.Web.PageController.action/2
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (mobilizon 1.0.7) lib/web/controllers/page_controller.ex:1: Mobilizon.Web.PageController.phoenix_controller_pipeline/2
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (mobilizon 1.0.7) lib/web/endpoint.ex:1: Mobilizon.Web.Endpoint.plug_builder_call/2
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (mobilizon 1.0.7) lib/web/endpoint.ex:1: Mobilizon.Web.Endpoint.call/2
Jul 06 20:49:00 mobilizon mobilizon[4092]:         (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
```

**Comment by tykayn** [comment]
c'est une bonne question, faut que je mette à jour le tout aussi

**Comment by tykayn** [comment]
arf j'ai du temps pour la gérer en ce moment, mais je n'arrive pas à me connecter :C la vm me demande un mot de passe alors que je donne une clé ssh à utiliser

**Comment by bristow** [comment]
Il semblerait que ce soit reparti d'après @tykayn sur Masto : https://mobilizon.openstreetmap.fr/

**Comment by tykayn** [comment]
oui c'est reparti

**Comment by jocelynj** [comment]
On dirait que http://mobilizon.openstreetmap.fr/ (sans https) ne retourne pas de page. Est-ce que tu voudrais un redirect vers le https côté proxy ?

**Comment by tykayn** [comment]
@jocelynj volontiers pour la redirection vers https

**Comment by jocelynj** [comment]
Redirection https en place, merci pour la réinstallation!
